apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: elastic
  labels:
    k8s-app: metricbeat
data:
  # This module requires `kube-state-metrics` up and running under `kube-system` namespace
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
      - state_node
      - state_deployment
      - state_replicaset
      - state_pod
      - state_container
      - state_cronjob
      - state_resourcequota
      - event
      period: 10s
      host: ${NODE_NAME}
      hosts: ["kube-state-metrics.kube-system:8080"]

    - module: mysql
      metricsets: ["status"]
      hosts: ["tcp(10.10.115.38:3306)/"]
      username: root
      password: tIohY1FpwA9T

    - module: redis
      metricsets: ["info", "keyspace"]
      enabled: true
      period: 30s
      hosts: ["10.10.115.38:6379"]
      password: Ambow99999999

#    - module: activemq
#      metricsets: ['broker', 'queue', 'topic']
#      period: 10s
#      hosts: ['10.10.115.84:32354']
#      path: '/api/?ignoreErrors=true&canonicalNaming=false'
#      username: admin
#      password: Ambow99999999