---

- name: elasticsearch 确认数据日志目录存在
  file:
    path: "{{ item.value }}"
    state: directory
    mode: '0755'
    # recurse: yes
    owner: elasticsearch
    group: elasticsearch
  with_dict: "{{ elasticsearch_paths_config }}"

- name: elasticsearch 生成配置文件
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: elasticsearch 调整 jvm 参数
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
  notify: restart elasticsearch

