---

- name: elasticsearch rpm 库中导入 gpg key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    fingerprint: 4609 5ACC 8548 582C 1A26 99A9 D27D 666C D88E 42B4

- name: elasticsearch 添加 yum 仓库
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: elasticsearch 安装软件包
  yum:
    name: elasticsearch
    state: present
    enablerepo: elasticsearch
