---

packages:
- unzip
- net-tools
- jq

prepare_sysctl_config:
  net.ipv4.tcp_slow_start_after_idle: '0'
  net.core.rmem_max: '16777216'
  fs.inotify.max_user_watches: '524288'
  fs.file-max: '65535'
  fs.inotify.max_user_instances: '8192'
  fs.inotify.max_queued_events: '16384'
  vm.max_map_count: '262144'
  net.core.netdev_max_backlog: '16384'
  net.core.wmem_max: '16777216'
  net.core.somaxconn: '32768'
  net.ipv4.tcp_wmem: '4096 12582912 16777216'
  net.ipv4.ip_forward: '1'
  net.ipv4.tcp_max_syn_backlog: '8096'
  net.ipv4.tcp_rmem: '4096 12582912 16777216'
  net.ipv4.conf.all.rp_filter: '0'
  net.ipv4.conf.default.rp_filter: '0'
  net.ipv4.conf.default.arp_announce: '2'
  net.ipv4.conf.lo.arp_announce: '2'
  net.ipv4.conf.all.arp_announce: '2'
  net.ipv6.conf.lo.disable_ipv6: '1'
  net.ipv6.conf.all.disable_ipv6: '1'
  net.ipv6.conf.default.disable_ipv6: '1'
